### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by omgmog** [AllThingsSmitty/jquery-your-mom-should-know#1]
Just raising this, because though it's nice to provide snippets for people (or their mothers), it's not nice to provide bad/mis information.

## Deprecated methods
You're using the deprecated (since jQuery 1.8!) old syntax for binds, e.g.

``` javascript
$('something').error(function () {});
```

You should be using the `.on()` syntax:

``` javascript
$('something').on('error', function () {});
```

This affects the following:

- `.error()`
- `.load()`
- `.click()`

## Setting an element property
You should be using `.prop()` to set the `disabled` property, since jQuery 1.6:

``` javascript
$('input').prop('disabled', true);
```

From the docs for `.prop()`:

> The .prop() method is a convenient way to set the value of properties—especially when setting multiple properties, using values returned by a function, or setting values on multiple elements at once. 

## Using JavaScript where CSS will do

I take umbrage with your `:odd` example, because this can and should be done completely in CSS:

``` css
li:nth-child(odd) {
  background: #e8e8e8;
}
```

All modern browsers support CSS3 selectors, and if you've got to support older browsers you could apply classes in your HTML, rather than depending on jQuery for a visual effect.

## Making two elements the same height

This example works if you know which element will be the largest, but a better, more flexible method would be to loop over a set of elements, and set the height for them to the height of the tallest element:

``` javascript
var $columns = $('.column');
var height = 0;
$columns.each(function () {
  if ($(this).height() > height) {
    height = $(this).height();
  }
});
$columns.height(height);
```

**Comment by AllThingsSmitty** [comment]
@omgmog thanks, I appreciate it! I'll look these over and work on integrating.

**Comment by AllThingsSmitty** [comment]
@omgmog great suggestions! Added to [859de9a423])(https://github.com/AllThingsSmitty/jquery-your-mom-should-know/commit/859de9a4234fc30c0718ea53511e6477c8f799a0)  :+1:

**Comment by omgmog** [comment]
:+1:
